custom:
  serverless-offline:
    httpPort: 8888

plugins:
  - serverless-offline
service: serverless-graphql
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
functions:
  graphql:
    handler: functions/graphql/index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
