custom:
  serverless-offline:
    httpPort: 8888
    corsAllowHeaders: "*"

plugins:
  - serverless-offline
service: serverless-graphql
provider:
  name: aws
  runtime: nodejs12.x

functions:
  graphql:
    handler: functions/graphql/index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
  login:
    handler: functions/auth/login.handler
    events:
      - http:
          path: auth/login
          method: post
          cors: true
      - http:
          path: auth/login
          method: get
          cors: true
  logout:
    handler: functions/auth/logout.handler
    events:
      - http:
          path: auth/logout
          method: post
          cors: true
      - http:
          path: auth/logout
          method: get
          cors: true
