custom:
  serverless-offline:
    httpPort: 8888
    corsAllowHeaders: "*"

plugins:
  - serverless-offline
service: serverless-graphql
provider:
  name: aws
  runtime: nodejs12.x

functions:
  graphql:
    handler: functions/graphql/index.handler
    events:
      - http:
          path: graphql
          method: post
          cors:
            origin: "*"
            headers: "*"
            allowCredentials: false
      - http:
          path: graphql
          method: get
          cors:
            origin: "*"
            headers: "*"
            allowCredentials: false
